### ISSUE TITLE
Different results using Demo or Code

### ISSUE THREAD

**Issue by filipeperdigaosousa** [jaimeiniesta/metainspectordemo#5]
Hi, 

I just forked this repo, trying to test the metainspector gem, and I saw the results of url scraping with your demo website are different from the results we can achieve with the source code.

As I can see, with your demo it's possible to scrape youtube urls, without being blocked by the cookies consent page.
How can we reproduce similar results?

**Comment by jaimeiniesta** [comment]
Hello!

The code used in the demo is the same from this repo. The only difference is the IP you're making the request from - I can also reproduce that in my dev machine, I also get the cookies consent wall when I run it from my office. But the same code, deployed on Heroku, does not get it.

This entirely depends on the website you're scraping. In this case, Youtube is deciding that an IP belonging to Heroku can pass freely, but an IP coming from our offices or homes, requires that cookie consent wall.

This is not to say that you should host your app in Heroku, in other cases your requests will be blocked by other servers just because of that, as they're identified as an automated scrape. In these cases, faking an User-Agent string can be helpful:

https://github.com/metainspector/metainspector#headers
